-- Run once in Supabase SQL Editor to enable anonymous sermon analytics.
create table if not exists public.sermon_plays (
  id bigint generated by default as identity primary key,
  sermon_id uuid not null references public.sermons(id) on delete cascade,
  listener_id text not null,
  listened_seconds integer not null default 20,
  played_at timestamptz not null default now()
);
create index if not exists sermon_plays_sermon_id_idx on public.sermon_plays(sermon_id);
create index if not exists sermon_plays_played_at_idx on public.sermon_plays(played_at desc);
alter table public.sermon_plays enable row level security;
drop policy if exists "public can record plays" on public.sermon_plays;
create policy "public can record plays" on public.sermon_plays for insert to anon, authenticated with check (listened_seconds >= 20 and listened_seconds <= 86400);
drop policy if exists "admins can read plays" on public.sermon_plays;
create policy "admins can read plays" on public.sermon_plays for select to authenticated using (true);
