"use client";
import {useEffect,useState} from "react";
import Image from "next/image";
import Link from "next/link";
import {Play} from "lucide-react";
import type {Sermon} from "@/data/sermons";
import {Container} from "@/components/ui/Container";
import {useAudioPlayer} from "@/components/sermon/AudioPlayerProvider";

type Entry={sermon:Sermon;position:number;duration:number;updatedAt:number};
const KEY="vbc-sermon-progress-v1";
function time(s:number){const m=Math.floor(s/60),sec=Math.floor(s%60);return `${m}:${String(sec).padStart(2,"0")}`}
export function ContinueListening(){const [entries,setEntries]=useState<Entry[]>([]);const {play}=useAudioPlayer();useEffect(()=>{const load=()=>{try{const obj=JSON.parse(localStorage.getItem(KEY)||"{}");setEntries(Object.values(obj).filter((x:any)=>x?.sermon?.audioUrl&&x.position>=3&&(!x.duration||x.position/x.duration<.95)).sort((a:any,b:any)=>b.updatedAt-a.updatedAt).slice(0,4) as Entry[])}catch{setEntries([])}};load();window.addEventListener("vbc-progress-updated",load);window.addEventListener("storage",load);return()=>{window.removeEventListener("vbc-progress-updated",load);window.removeEventListener("storage",load)}},[]);if(!entries.length)return null;return <section className="py-8 sm:py-10"><Container><div className="mb-5 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-red-400">Pick up where you stopped</p><h2 className="vbc-display mt-1 text-3xl uppercase sm:text-4xl">Continue Listening</h2></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{entries.map(({sermon,position,duration})=>{const pct=duration?Math.min(100,position/duration*100):0;return <article key={sermon.id} className="overflow-hidden rounded-2xl border border-white/15 bg-gradient-to-br from-[#28158e]/70 via-[#25167f]/55 to-[#160b58]/70 shadow-[0_15px_45px_rgba(8,0,65,.25)] backdrop-blur-xl"><div className="flex gap-3 p-3"><Link href={`/sermon/${sermon.slug}`} className="relative size-20 shrink-0 overflow-hidden rounded-xl bg-white/5"><Image src={sermon.image} alt={sermon.title} fill className="object-cover" sizes="80px"/></Link><div className="min-w-0 flex-1"><p className="text-[9px] font-bold uppercase tracking-[.14em] text-red-300">{sermon.series}</p><Link href={`/sermon/${sermon.slug}`} className="mt-1 block line-clamp-2 text-sm font-bold leading-tight text-white">{sermon.title}</Link><button onClick={()=>play(sermon)} className="mt-3 inline-flex items-center gap-1.5 rounded-full bg-white px-3 py-1.5 text-[10px] font-extrabold text-[#170059] transition active:scale-95"><Play size={11} fill="currentColor"/> Resume {time(position)}</button></div></div><div className="h-1 bg-white/10"><div className="h-full bg-[#ff1738]" style={{width:`${pct}%`}}/></div></article>})}</div></Container></section>}
