"use client";
import {createContext,useContext,useEffect,useMemo,useState} from "react";
import Image from "next/image";
import {Check,ListMusic,Plus,X} from "lucide-react";
import type {Sermon} from "@/data/sermons";

export type Playlist={id:string;name:string;description?:string;sermonIds:string[];createdAt:string;updatedAt?:string};
type Toast={title:string;message:string;image?:string}|null;
type Ctx={playlists:Playlist[];openAdd:(s:Sermon)=>void;create:(name:string,sermonId?:string,description?:string)=>void;remove:(pid:string,sid:string)=>void;deletePlaylist:(pid:string)=>void;rename:(pid:string,name:string)=>void};
const KEY="vbc-sermon-playlists-v1";
const Context=createContext<Ctx|null>(null);
export function PlaylistProvider({children}:{children:React.ReactNode}){
 const [playlists,setPlaylists]=useState<Playlist[]>([]),[target,setTarget]=useState<Sermon|null>(null),[name,setName]=useState(""),[toast,setToast]=useState<Toast>(null);
 useEffect(()=>{try{setPlaylists(JSON.parse(localStorage.getItem(KEY)||"[]"))}catch{}},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(null),2800);return()=>clearTimeout(t)},[toast]);
 function save(next:Playlist[]){setPlaylists(next);localStorage.setItem(KEY,JSON.stringify(next))}
 function create(n:string,sid?:string,description?:string){const clean=n.trim();if(!clean)return;const next={id:`pl_${Date.now()}`,name:clean,description:description?.trim()||"",sermonIds:sid?[sid]:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};save([next,...playlists]);setName("");setTarget(null);setToast({title:"Playlist created",message:sid?`Added to ${clean}`:`${clean} is ready`,image:sid?target?.image:undefined})}
 function toggle(pid:string,sid:string){const p=playlists.find(x=>x.id===pid);if(!p)return;const added=!p.sermonIds.includes(sid);save(playlists.map(x=>x.id===pid?{...x,updatedAt:new Date().toISOString(),sermonIds:added?[...x.sermonIds,sid]:x.sermonIds.filter(v=>v!==sid)}:x));setToast({title:added?"Added to playlist":"Removed from playlist",message:p.name,image:target?.image})}
 const value=useMemo(()=>({playlists,openAdd:setTarget,create,remove:(pid:string,sid:string)=>{const p=playlists.find(x=>x.id===pid);save(playlists.map(x=>x.id===pid?{...x,updatedAt:new Date().toISOString(),sermonIds:x.sermonIds.filter(v=>v!==sid)}:x));if(p)setToast({title:"Removed from playlist",message:p.name})},deletePlaylist:(pid:string)=>save(playlists.filter(p=>p.id!==pid)),rename:(pid:string,n:string)=>save(playlists.map(p=>p.id===pid?{...p,name:n.trim()||p.name,updatedAt:new Date().toISOString()}:p))}),[playlists,target]);
 return <Context.Provider value={value}>{children}{target&&<div className="playlist-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setTarget(null)}><div className="playlist-add-popover"><div className="playlist-modal-head"><div><p className="playlist-eyebrow">Add to playlist</p><h3>Add to Playlist</h3></div><button onClick={()=>setTarget(null)} className="playlist-icon-btn" aria-label="Close"><X size={18}/></button></div><p className="playlist-target-title">{target.title}</p><div className="playlist-check-list">{playlists.map(p=>{const added=p.sermonIds.includes(target.id);return <button key={p.id} onClick={()=>toggle(p.id,target.id)} className="playlist-check-row"><span className={`playlist-checkbox ${added?"is-checked":""}`}>{added&&<Check size={13}/>}</span><span><b>{p.name}</b><small>{p.sermonIds.length} sermon{p.sermonIds.length===1?"":"s"}</small></span></button>})}{!playlists.length&&<p className="playlist-empty-mini">No playlists yet. Create your first one below.</p>}</div><form onSubmit={e=>{e.preventDefault();create(name,target.id)}} className="playlist-create-inline"><Plus size={17}/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Create New Playlist"/><button type="submit">Create</button></form></div></div>}{toast&&<div className="playlist-toast" role="status">{toast.image&&<div className="playlist-toast-art"><Image src={toast.image} alt="" fill className="object-cover" sizes="48px"/></div>}<div className="playlist-toast-check"><Check size={16}/></div><div><b>{toast.title}</b><span>{toast.message}</span></div><button onClick={()=>setToast(null)} aria-label="Dismiss"><X size={15}/></button></div>}</Context.Provider>
}
export function usePlaylists(){const c=useContext(Context);if(!c)throw new Error("usePlaylists must be inside PlaylistProvider");return c}
export function AddToPlaylistButton({sermon,compact=false}:{sermon:Sermon;compact?:boolean}){const {openAdd}=usePlaylists();return <button type="button" onClick={e=>{e.preventDefault();e.stopPropagation();openAdd(sermon)}} title="Add to playlist" className={compact?"grid size-9 place-items-center rounded-full bg-white/90 text-[#170059] shadow-lg hover:scale-105":"flex items-center gap-2"}><ListMusic size={compact?16:22}/>{!compact&&<span>Add to Playlist</span>}</button>}
